/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zy_mbk_NativeUtil */

#ifndef _Included_com_zy_mbk_NativeUtil
#define _Included_com_zy_mbk_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zy_mbk_NativeUtil
 * Method:    getSha1StringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zy_mbk_NativeUtil_getSha1StringNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
